services:
  - type: web
    name: opencall-monitor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEVELOPMENT_AID_EMAIL
        sync: false
      - key: DEVELOPMENT_AID_PASSWORD
        sync: false
